### PR TITLE
Add support for Vyper decimal10 ABI type

### PR DESCRIPTION
**Pull request by davesque**
*Note: This branch is rooted at the current `registry` branch head.*

### What was wrong?

Must add support for Vyper `decimal10` type.  Issue ticket here:
https://github.com/ethereum/eth-abi/issues/39

Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
I must be missing something.  I don't see any code here for `decimal` type support?

**Comment by carver** [comment]
Yeah, I think github auto-closed this one because it had the same tip as the registry PR.

**Comment by davesque** [comment]
Yep sorry about that.  I meant to mention this in today's standup.  I had opened an empty PR which I guess github let me do since it was based on the head of the unmerged `registry` branch.  But then, when I merged in the registry, github automatically closed the vyper pull request.  I guess there's not really any way to open an empty PR.

**Comment by pipermerriam** [comment]
It's ok, I was just confused.  Makes sense.

**Pull request merged**
