### PR TITLE
Update officially supported python versions

### PR DESCRIPTION
**Pull request by davesque**
### What was wrong?

Looks like web3.py only tests against python 3.6 and 3.7.

### How was it fixed?

Updated testing config to do the same.

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Review by carver — COMMENTED** [review]
Re: lint -- you could make isort fixups easy by adding the `lint-roll` make command from https://github.com/ethereum/web3.py/blob/a22c6cc898df6665814aafcfb797fc095201a470/Makefile#L27-L29

:+1: for dropping py3.5 in v2

:-1: for dropping pypy3 -- might as well keep support alive as long as possible in as many libraries as possible, until it becomes a huge burden

**Comment by davesque** [comment]
Yep, I'll add that.

Wasn't there some talk about dropping pypy support?  I dunno.  I feel like it's a bit of a hassle to have to remember which packages do or don't support pypy.  Seems better to just decide one way or another that we support pypy.  Another problem I have with supporting pypy is that it often lags behind the current python sub version by about two versions.  That limits the possible use of nice, next gen language features.

**Comment by davesque** [comment]
So dropping python3.5 support but keeping pypy3 support is really like doing nothing because pypy3 only implements 3.5 last I checked.

**Comment by carver** [comment]
> I feel like it's a bit of a hassle to have to remember which packages do or don't support pypy. Seems better to just decide one way or another that we support pypy.

My logic is that it's much easier to notice that you're adding a pypy-unfriendly library in a failing PR than it is to go re-audit every library and every dependency of every library we maintain.

> So dropping python3.5 support but keeping pypy3 support is really like doing nothing because pypy3 only implements 3.5 last I checked.

Argh, okay, fine. I hate py3.5 slightly more than I hate having to go back and make every single library re-support pypy3 someday.

**Review by carver — APPROVED** [review]

**Comment by davesque** [comment]
Hehe, yay! 🎉

**Pull request merged**
