### PR TITLE
Added function type support (pipermerriam/web3.py) Issue #164

### PR DESCRIPTION
**Pull request by ghost**
These changes add support for the function type in solidity (ethereum/solidity#1122).

### CODE REVIEW

**Comment by pipermerriam** [comment]
FYI, test failure is unrelated to this PR.  I'll handle addressing it.

**Comment by pipermerriam** [comment]
Can you get a few tests added for this new type.

* https://github.com/pipermerriam/ethereum-abi-utils/blob/master/tests/encoding/test_encode_single.py
* https://github.com/pipermerriam/ethereum-abi-utils/blob/master/tests/decoding/test_decode_single_type.py

**Comment by reiven** [comment]
ping

**Comment by pipermerriam** [comment]
closed in favor of #15

**Pull request closed without merging**
