### PR TITLE
Add support for non-standard packed mode

### PR DESCRIPTION
**Pull request by davesque**
### What was wrong?

See issue #67 .

### How was it fixed?

Added `registry_packed` registry for packed mode encoders.  Added packed mode encoder classes.  Added `encode_single_packed` and `encode_abi_packed` functions.

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Review by pipermerriam — APPROVED** [review]
My eyes admittedly glazed over while perusing the tests.  It looks a lot like packed encodings were easy to implement within the existing encoder/decoder framework

**Review by carver — APPROVED** [review]
LGTM

**Comment by davesque** [comment]
@pipermerriam Yeah, it was pretty straight forward.  The tests were the hardest point as you allude to.  The thing that probably seems most confusing is that little utility function `words`.  To keep you in the loop, my goals with creating that were:

* To have a way to describe the expected results of encodings without using Python's very verbose literal byte syntax
* To avoid having to literally spell out all padding bytes (of which there are many with 32 byte wide words)
* To be able to use more or less the same encoding "description" for both standard and packed mode

**Comment by davesque** [comment]
Ugh.  Accidentally clicked the close button.  I wish Github had a confirmation dialogue for that or something :/.

**Pull request merged**
