### PR TITLE
Dynamic array support

### LINKED ISSUE #94: Backport dynamic array encoding to v1
### What was wrong?

#93 support is not available in a stable version (v1).

### How can it be fixed?

Backport #92 to the v1 branch

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

Closes #94 

### How was it fixed?

Backported #90 and #92 sequentially (plus some in-commit patches to make it v1-compatible)

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by carver** [comment]
@davesque Have you seen this ~"examples too slow" error from hypothesis on pypy before? I'm sure I can dig in and figure it out, just curious if you had a quick fix handy.

**Comment by pipermerriam** [comment]
@carver probably worth just creating an issue and adding the `too_slow` to the ignored health checks.

**Comment by carver** [comment]
Ok, ready for review, then.

**Comment by davesque** [comment]
@carver My "quick fix" lately has just been to re-run the failed job until is passes :).  I believe the failing tests are the ones which do property testing to check coder class behavior.  They should actually be deleted since they aren't that useful.  That's the *real* fix.

**Comment by davesque** [comment]
@carver Actually, I was wrong.  I think the issue was being caused by a recursive strategy that was generating too many leaves.  I made a one-line PR for that issue specifically.  I think you can revert the fix you added to this PR.

**Comment by carver** [comment]
Cool, I removed the slow test exception. I'll wait to merge until you review, @davesque

**Review by davesque — APPROVED** [review]
I think this is good to go, Jason.

**Pull request merged**
