### PR TITLE
reduce truncation in errors

### PR DESCRIPTION
**Pull request by charles-cooper**
allow more int values to be fully printed in errors. the current code
truncates a lot of integer values which fit in 256 bits, which reduces
helpfulness of the error message when debugging.

## What was wrong?

Issue #

## How was it fixed?

Summary of approach.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/eth-abi/blob/master/newsfragments/README.md)

[//]: # (See: https://eth-abi.readthedocs.io/en/latest/contributing.html#pull-requests)
- [x] Add entry to the [release notes](https://github.com/ethereum/eth-abi/blob/master/newsfragments/README.md)

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by charles-cooper** [comment]
@kclowes @fselmo is it possible to get a review on this? I can fix the merge conflicts if the approach looks ok

**Comment by kclowes** [comment]
Thanks for the ping, @charles-cooper. This change looks fine to me. If you don't mind fixing the merge conflicts I can probably get this in next week. Thanks!

edit: if you don't hear from me next week, feel free to tag me again :)

**Comment by charles-cooper** [comment]
@kclowes resolved!

**Comment by charles-cooper** [comment]
@kclowes resolved!

**Review by kclowes — APPROVED** [review]
Thanks! I'll add a newsfragment and merge once tests pass!

**Comment by charles-cooper** [comment]
i see that this breaks some specific tests:

Screenshot from 2022-07-07 16-19-00

@kclowes actually i think it would be good to remove the `abbr()` function altogether? it's not friendly for debugging, and as downstream tools (like pytest) have settings to truncate output anyways -- i can't really think of a situation where you want to truncate the info in the exception which isn't already handled by downstream tooling

**Comment by kclowes** [comment]
Yeah, that's a fair point. I just changed the expectation of the tests for now. I think it does make sense to remove `abbr` in the next major release. What version of `eth-abi` are you using?

**Comment by charles-cooper** [comment]
> Yeah, that's a fair point. I just changed the expectation of the tests for now. I think it does make sense to remove `abbr` in the next major release. What version of `eth-abi` are you using?

2.1.1 and 3.0.0

**Comment by kclowes** [comment]
> 2.1.1 and 3.0.0

Cool. I'll try and get those released next week. Thanks again!

**Comment by charles-cooper** [comment]
Thanks @kclowes !!

**Comment by kclowes** [comment]
@charles-cooper both 2.2.0 and 3.0.1 are out with this fix!

**Pull request merged**
